/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as MainlayoutRouteRouteImport } from './routes/_mainlayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as MainlayoutHomeRouteImport } from './routes/_mainlayout/home'
import { Route as MainlayoutRecurrentExpensesRouteRouteImport } from './routes/_mainlayout/recurrent-expenses/route'
import { Route as MainlayoutExpensesRouteRouteImport } from './routes/_mainlayout/expenses/route'
import { Route as MainlayoutRecurrentExpensesIndexRouteImport } from './routes/_mainlayout/recurrent-expenses/index'
import { Route as MainlayoutExpensesIndexRouteImport } from './routes/_mainlayout/expenses/index'
import { Route as MainlayoutRecurrentExpensesNewRouteImport } from './routes/_mainlayout/recurrent-expenses/new'
import { Route as MainlayoutExpensesNewRouteImport } from './routes/_mainlayout/expenses/new'
import { Route as MainlayoutExpensesExpenseIdRouteImport } from './routes/_mainlayout/expenses/$expenseId'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainlayoutRouteRoute = MainlayoutRouteRouteImport.update({
  id: '/_mainlayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainlayoutHomeRoute = MainlayoutHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => MainlayoutRouteRoute,
} as any)
const MainlayoutRecurrentExpensesRouteRoute =
  MainlayoutRecurrentExpensesRouteRouteImport.update({
    id: '/recurrent-expenses',
    path: '/recurrent-expenses',
    getParentRoute: () => MainlayoutRouteRoute,
  } as any)
const MainlayoutExpensesRouteRoute = MainlayoutExpensesRouteRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => MainlayoutRouteRoute,
} as any)
const MainlayoutRecurrentExpensesIndexRoute =
  MainlayoutRecurrentExpensesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => MainlayoutRecurrentExpensesRouteRoute,
  } as any)
const MainlayoutExpensesIndexRoute = MainlayoutExpensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainlayoutExpensesRouteRoute,
} as any)
const MainlayoutRecurrentExpensesNewRoute =
  MainlayoutRecurrentExpensesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => MainlayoutRecurrentExpensesRouteRoute,
  } as any)
const MainlayoutExpensesNewRoute = MainlayoutExpensesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MainlayoutExpensesRouteRoute,
} as any)
const MainlayoutExpensesExpenseIdRoute =
  MainlayoutExpensesExpenseIdRouteImport.update({
    id: '/$expenseId',
    path: '/$expenseId',
    getParentRoute: () => MainlayoutExpensesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/expenses': typeof MainlayoutExpensesRouteRouteWithChildren
  '/recurrent-expenses': typeof MainlayoutRecurrentExpensesRouteRouteWithChildren
  '/home': typeof MainlayoutHomeRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/expenses/$expenseId': typeof MainlayoutExpensesExpenseIdRoute
  '/expenses/new': typeof MainlayoutExpensesNewRoute
  '/recurrent-expenses/new': typeof MainlayoutRecurrentExpensesNewRoute
  '/expenses/': typeof MainlayoutExpensesIndexRoute
  '/recurrent-expenses/': typeof MainlayoutRecurrentExpensesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/home': typeof MainlayoutHomeRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/expenses/$expenseId': typeof MainlayoutExpensesExpenseIdRoute
  '/expenses/new': typeof MainlayoutExpensesNewRoute
  '/recurrent-expenses/new': typeof MainlayoutRecurrentExpensesNewRoute
  '/expenses': typeof MainlayoutExpensesIndexRoute
  '/recurrent-expenses': typeof MainlayoutRecurrentExpensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_mainlayout': typeof MainlayoutRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_mainlayout/expenses': typeof MainlayoutExpensesRouteRouteWithChildren
  '/_mainlayout/recurrent-expenses': typeof MainlayoutRecurrentExpensesRouteRouteWithChildren
  '/_mainlayout/home': typeof MainlayoutHomeRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_mainlayout/expenses/$expenseId': typeof MainlayoutExpensesExpenseIdRoute
  '/_mainlayout/expenses/new': typeof MainlayoutExpensesNewRoute
  '/_mainlayout/recurrent-expenses/new': typeof MainlayoutRecurrentExpensesNewRoute
  '/_mainlayout/expenses/': typeof MainlayoutExpensesIndexRoute
  '/_mainlayout/recurrent-expenses/': typeof MainlayoutRecurrentExpensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/expenses'
    | '/recurrent-expenses'
    | '/home'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/expenses/$expenseId'
    | '/expenses/new'
    | '/recurrent-expenses/new'
    | '/expenses/'
    | '/recurrent-expenses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/expenses/$expenseId'
    | '/expenses/new'
    | '/recurrent-expenses/new'
    | '/expenses'
    | '/recurrent-expenses'
  id:
    | '__root__'
    | '/'
    | '/_mainlayout'
    | '/auth'
    | '/_mainlayout/expenses'
    | '/_mainlayout/recurrent-expenses'
    | '/_mainlayout/home'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_mainlayout/expenses/$expenseId'
    | '/_mainlayout/expenses/new'
    | '/_mainlayout/recurrent-expenses/new'
    | '/_mainlayout/expenses/'
    | '/_mainlayout/recurrent-expenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainlayoutRouteRoute: typeof MainlayoutRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_mainlayout': {
      id: '/_mainlayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainlayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_mainlayout/home': {
      id: '/_mainlayout/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof MainlayoutHomeRouteImport
      parentRoute: typeof MainlayoutRouteRoute
    }
    '/_mainlayout/recurrent-expenses': {
      id: '/_mainlayout/recurrent-expenses'
      path: '/recurrent-expenses'
      fullPath: '/recurrent-expenses'
      preLoaderRoute: typeof MainlayoutRecurrentExpensesRouteRouteImport
      parentRoute: typeof MainlayoutRouteRoute
    }
    '/_mainlayout/expenses': {
      id: '/_mainlayout/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof MainlayoutExpensesRouteRouteImport
      parentRoute: typeof MainlayoutRouteRoute
    }
    '/_mainlayout/recurrent-expenses/': {
      id: '/_mainlayout/recurrent-expenses/'
      path: '/'
      fullPath: '/recurrent-expenses/'
      preLoaderRoute: typeof MainlayoutRecurrentExpensesIndexRouteImport
      parentRoute: typeof MainlayoutRecurrentExpensesRouteRoute
    }
    '/_mainlayout/expenses/': {
      id: '/_mainlayout/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof MainlayoutExpensesIndexRouteImport
      parentRoute: typeof MainlayoutExpensesRouteRoute
    }
    '/_mainlayout/recurrent-expenses/new': {
      id: '/_mainlayout/recurrent-expenses/new'
      path: '/new'
      fullPath: '/recurrent-expenses/new'
      preLoaderRoute: typeof MainlayoutRecurrentExpensesNewRouteImport
      parentRoute: typeof MainlayoutRecurrentExpensesRouteRoute
    }
    '/_mainlayout/expenses/new': {
      id: '/_mainlayout/expenses/new'
      path: '/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof MainlayoutExpensesNewRouteImport
      parentRoute: typeof MainlayoutExpensesRouteRoute
    }
    '/_mainlayout/expenses/$expenseId': {
      id: '/_mainlayout/expenses/$expenseId'
      path: '/$expenseId'
      fullPath: '/expenses/$expenseId'
      preLoaderRoute: typeof MainlayoutExpensesExpenseIdRouteImport
      parentRoute: typeof MainlayoutExpensesRouteRoute
    }
  }
}

interface MainlayoutExpensesRouteRouteChildren {
  MainlayoutExpensesExpenseIdRoute: typeof MainlayoutExpensesExpenseIdRoute
  MainlayoutExpensesNewRoute: typeof MainlayoutExpensesNewRoute
  MainlayoutExpensesIndexRoute: typeof MainlayoutExpensesIndexRoute
}

const MainlayoutExpensesRouteRouteChildren: MainlayoutExpensesRouteRouteChildren =
  {
    MainlayoutExpensesExpenseIdRoute: MainlayoutExpensesExpenseIdRoute,
    MainlayoutExpensesNewRoute: MainlayoutExpensesNewRoute,
    MainlayoutExpensesIndexRoute: MainlayoutExpensesIndexRoute,
  }

const MainlayoutExpensesRouteRouteWithChildren =
  MainlayoutExpensesRouteRoute._addFileChildren(
    MainlayoutExpensesRouteRouteChildren,
  )

interface MainlayoutRecurrentExpensesRouteRouteChildren {
  MainlayoutRecurrentExpensesNewRoute: typeof MainlayoutRecurrentExpensesNewRoute
  MainlayoutRecurrentExpensesIndexRoute: typeof MainlayoutRecurrentExpensesIndexRoute
}

const MainlayoutRecurrentExpensesRouteRouteChildren: MainlayoutRecurrentExpensesRouteRouteChildren =
  {
    MainlayoutRecurrentExpensesNewRoute: MainlayoutRecurrentExpensesNewRoute,
    MainlayoutRecurrentExpensesIndexRoute:
      MainlayoutRecurrentExpensesIndexRoute,
  }

const MainlayoutRecurrentExpensesRouteRouteWithChildren =
  MainlayoutRecurrentExpensesRouteRoute._addFileChildren(
    MainlayoutRecurrentExpensesRouteRouteChildren,
  )

interface MainlayoutRouteRouteChildren {
  MainlayoutExpensesRouteRoute: typeof MainlayoutExpensesRouteRouteWithChildren
  MainlayoutRecurrentExpensesRouteRoute: typeof MainlayoutRecurrentExpensesRouteRouteWithChildren
  MainlayoutHomeRoute: typeof MainlayoutHomeRoute
}

const MainlayoutRouteRouteChildren: MainlayoutRouteRouteChildren = {
  MainlayoutExpensesRouteRoute: MainlayoutExpensesRouteRouteWithChildren,
  MainlayoutRecurrentExpensesRouteRoute:
    MainlayoutRecurrentExpensesRouteRouteWithChildren,
  MainlayoutHomeRoute: MainlayoutHomeRoute,
}

const MainlayoutRouteRouteWithChildren = MainlayoutRouteRoute._addFileChildren(
  MainlayoutRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainlayoutRouteRoute: MainlayoutRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
